Repository DDAL-KKAK-DOT/DDALKKAK, pull requests merged in 2025-06, with the labels that each got.

#25 LLM과 POST 연결
  backend/data_model/career.py
  backend/data_model/inputProfile.py
  backend/data_model/project.py
  backend/gemini_test.py
  backend/service.py
  backend/utils_fetch.py
Labels: BE

#27 ♻️ Modified profileInfo to JSON
  backend/data_model/outputProfile.py
  backend/gemini_test.py
  backend/service.py
Labels: BE

#29 ✨ Implement AI Resume Setup Page with react-hook-form
  frontend/.husky/pre-commit
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/apiClient.ts
  frontend/src/apis/fetchAIResume.ts
  frontend/src/app/resume/start/components/ActivityLinksField.tsx
  frontend/src/app/resume/start/components/EducationField.tsx
  frontend/src/app/resume/start/components/RequiredTextField.tsx
  frontend/src/app/resume/start/components/ResumeForm.tsx
  frontend/src/app/resume/start/page.tsx
  frontend/src/components/Field/Section.tsx
  frontend/src/components/Field/TextField.tsx
  frontend/src/components/IconButton/IconButton.tsx
  frontend/src/hooks/queries/useSubmitAIResumeMutation.ts
  frontend/src/hooks/useLocalStorageObject.ts
  frontend/src/types/resume.ts
Labels: FE

#38 🚀 Deploy Edit Page with PDF feature
  frontend/src/apis/apiClient.ts
  frontend/src/apis/uploadResume.ts
  frontend/src/app/layout.tsx
  frontend/src/app/resume/edit/components/ResumeForm.tsx
  frontend/src/app/resume/edit/components/ResumePreview/ResumePreview.tsx
  frontend/src/app/resume/edit/components/ResumePreview/ResumePreviewType1.module.css
  frontend/src/app/resume/edit/components/ResumePreview/ResumePreviewType1.tsx
  frontend/src/app/resume/edit/components/ResumeTypeSelector.tsx
  frontend/src/app/resume/edit/components/sections/CareersSection.tsx
  frontend/src/app/resume/edit/page.tsx
  frontend/src/app/resume/start/components/ResumeForm.tsx
  frontend/src/components/Button/Button.styles.ts
  frontend/src/components/Button/buttonVariants.ts
  frontend/src/components/ResizerBar/ResizerBar.tsx
  frontend/src/components/ResizerBar/useResizableForm.ts
  frontend/src/components/layout/DefaultLayout.tsx
  frontend/src/hooks/queries/useResumeUpload.ts
  frontend/src/utils/resumeHtml.ts
Labels: FE, 🚀 CD

#40 🐛 GET APIs
  backend/sample_data/output_data.py
  backend/service.py
Labels: BE

#46 :sparkles: Added support for ARM arch
  backend/utils_fetch.py
Labels: BE, Feature

#48 ♻️ auto merge CI with No Label
  .github/workflows/auto-merge.yml
Labels: BE, 👷 CI

#63 :recycle: prompt to few-shot
  backend/gemini_client.py
Labels: BE, automerge

#68 ♻️ No Label merge
  .github/workflows/auto-merge.yml
Labels: BE, 👷 CI
